Update laravel.yml

diff --git a/.github/workflows/laravel.yml b/.github/workflows/laravel.yml
--- a/.github/workflows/laravel.yml
+++ b/.github/workflows/laravel.yml
@@ -31,6 +31,19 @@ jobs:
         TAG_VALUE=$(aws ec2 describe-instances --instance-ids $AWS_INSTANCE_ID \--query "Reservations[].Instances[].Tags[?Key=='$AWS_TAG'].Value" \--output text)
         echo "Instance Tag Value:" $TAG_VALUE   
         echo "Secret variable:" $AWS_TAG_VALUE
+        
+     - name: Compare Tag Value with Secret
+       id: compare-tag
+       run: |
+         if [[ "$TAG_VALUE" == "$AWS_TAG_VALUE" ]]; then
+         echo "Tag values are the same. Running git pull command..."
+         cd /opt/laravel
+         touch sample.txt
+         else
+         echo "Tag values are different. Displaying error message..."
+         echo "Error: Tag values do not match."
+         exit 1
+         fi
      
        
         
